/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SenderType = IDL.Variant({
  'whatsapp' : IDL.Null,
  'email_domain' : IDL.Null,
});
export const SenderIdentityId = IDL.Nat;
export const WarmupPhase = IDL.Variant({
  'unlimited' : IDL.Null,
  'phase1' : IDL.Null,
  'phase2' : IDL.Null,
  'phase3' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const SenderIdentity = IDL.Record({
  'id' : SenderIdentityId,
  'reputationScore' : IDL.Nat,
  'warmupPhase' : WarmupPhase,
  'createdAt' : Timestamp,
  'totalReplied' : IDL.Nat,
  'totalSent' : IDL.Nat,
  'totalDelivered' : IDL.Nat,
  'totalBounced' : IDL.Nat,
  'blockedCount' : IDL.Nat,
  'senderType' : SenderType,
  'identifier' : IDL.Text,
  'totalOptOut' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeadId = IDL.Nat;
export const NoteId = IDL.Nat;
export const CreateClientInput = IDL.Record({
  'businessName' : IDL.Text,
  'leadId' : LeadId,
  'startDate' : Timestamp,
});
export const ClientId = IDL.Nat;
export const ClientMetrics = IDL.Record({
  'revenue' : IDL.Float64,
  'leads' : IDL.Nat,
  'traffic' : IDL.Nat,
  'conversions' : IDL.Nat,
});
export const Client = IDL.Record({
  'id' : ClientId,
  'metrics' : ClientMetrics,
  'businessName' : IDL.Text,
  'reportDate' : Timestamp,
  'leadId' : LeadId,
  'startDate' : Timestamp,
});
export const ConversionScriptId = IDL.Nat;
export const ScriptType = IDL.Variant({
  'chat_suggestion' : IDL.Null,
  'call_script' : IDL.Null,
  'email_sequence' : IDL.Null,
});
export const ConversionScript = IDL.Record({
  'id' : ConversionScriptId,
  'serviceType' : IDL.Text,
  'discoveryQuestions' : IDL.Vec(IDL.Text),
  'opener' : IDL.Text,
  'scriptType' : ScriptType,
  'createdAt' : IDL.Int,
  'painPoint' : IDL.Text,
  'budgetTier' : IDL.Text,
  'valueProp' : IDL.Text,
  'closingTalk' : IDL.Text,
  'objectionHandlers' : IDL.Vec(
    IDL.Record({
      'softResponse' : IDL.Text,
      'directResponse' : IDL.Text,
      'objection' : IDL.Text,
    })
  ),
});
export const SuggestionPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const CreateSuggestionInput = IDL.Record({
  'title' : IDL.Text,
  'clientId' : ClientId,
  'estimatedImpact' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priority' : SuggestionPriority,
  'weekOf' : Timestamp,
});
export const SuggestionId = IDL.Nat;
export const GrowthSuggestion = IDL.Record({
  'id' : SuggestionId,
  'title' : IDL.Text,
  'clientId' : ClientId,
  'estimatedImpact' : IDL.Text,
  'description' : IDL.Text,
  'implemented' : IDL.Bool,
  'category' : IDL.Text,
  'priority' : SuggestionPriority,
  'dismissed' : IDL.Bool,
  'weekOf' : Timestamp,
});
export const LandingPageNiche = IDL.Variant({
  'gym' : IDL.Null,
  'plumber' : IDL.Null,
  'cafe' : IDL.Null,
  'education' : IDL.Null,
  'agency' : IDL.Null,
  'salon' : IDL.Null,
  'real_estate' : IDL.Null,
  'restaurant' : IDL.Null,
  'medical' : IDL.Null,
});
export const LandingPageId = IDL.Nat;
export const LandingPageStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
  'archived' : IDL.Null,
});
export const LandingPageSection = IDL.Record({
  'hero' : IDL.Text,
  'ctaText' : IDL.Text,
  'painPoints' : IDL.Vec(IDL.Text),
  'formTitle' : IDL.Text,
  'beforeAfter' : IDL.Record({ 'after' : IDL.Text, 'before' : IDL.Text }),
  'testimonials' : IDL.Vec(
    IDL.Record({ 'name' : IDL.Text, 'quote' : IDL.Text, 'business' : IDL.Text })
  ),
  'subheadline' : IDL.Text,
});
export const LandingPage = IDL.Record({
  'id' : LandingPageId,
  'status' : LandingPageStatus,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'serviceDescription' : IDL.Text,
  'publishedAt' : IDL.Opt(IDL.Int),
  'estimatedConversionRate' : IDL.Nat,
  'estimatedLeadScore' : IDL.Nat,
  'targetBudget' : IDL.Text,
  'niche' : LandingPageNiche,
  'leadsCaptured' : IDL.Nat,
  'sections' : LandingPageSection,
});
export const CreateLeadInput = IDL.Record({
  'city' : IDL.Text,
  'leadScore' : IDL.Nat,
  'businessName' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'industry' : IDL.Text,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'proposal' : IDL.Null,
  'contacted' : IDL.Null,
});
export const LeadScoreBreakdown = IDL.Record({
  'seo' : IDL.Nat,
  'reviews' : IDL.Nat,
  'social' : IDL.Nat,
  'domainAge' : IDL.Nat,
  'website' : IDL.Nat,
});
export const ConsentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'granted' : IDL.Null,
  'withdrawn' : IDL.Null,
});
export const PriorityTag = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : LeadId,
  'status' : LeadStatus,
  'scoreBreakdown' : IDL.Opt(LeadScoreBreakdown),
  'consentStatus' : IDL.Opt(ConsentStatus),
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'leadScore' : IDL.Nat,
  'businessName' : IDL.Text,
  'website' : IDL.Text,
  'attemptCount' : IDL.Nat,
  'updatedAt' : Timestamp,
  'referredBy' : IDL.Opt(LeadId),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'leadSource' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'optedOut' : IDL.Bool,
  'priorityTag' : IDL.Opt(PriorityTag),
  'industry' : IDL.Text,
});
export const NoteType = IDL.Variant({
  'reminder' : IDL.Null,
  'note' : IDL.Null,
});
export const CreateNoteInput = IDL.Record({
  'content' : IDL.Text,
  'dueDate' : IDL.Opt(Timestamp),
  'noteType' : NoteType,
  'leadId' : LeadId,
});
export const Note = IDL.Record({
  'id' : NoteId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Timestamp),
  'noteType' : NoteType,
  'leadId' : LeadId,
});
export const CreateOutreachCampaignInput = IDL.Record({
  'businessName' : IDL.Text,
  'channels' : IDL.Vec(IDL.Text),
  'leadId' : LeadId,
});
export const OutreachCampaign = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'completedAt' : IDL.Opt(Timestamp),
  'startedAt' : Timestamp,
  'businessName' : IDL.Text,
  'totalMessages' : IDL.Nat,
  'channels' : IDL.Vec(IDL.Text),
  'leadId' : LeadId,
  'deliveredCount' : IDL.Nat,
  'repliedCount' : IDL.Nat,
});
export const CreateOutreachMessageInput = IDL.Record({
  'personalizedMessage' : IDL.Text,
  'businessName' : IDL.Text,
  'templateType' : IDL.Text,
  'dayNumber' : IDL.Nat,
  'leadId' : LeadId,
  'channel' : IDL.Text,
  'detectedProblem' : IDL.Text,
  'scheduledAt' : Timestamp,
});
export const OutreachMessage = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'deliveredAt' : IDL.Opt(Timestamp),
  'personalizedMessage' : IDL.Text,
  'bounceReason' : IDL.Text,
  'businessName' : IDL.Text,
  'sentAt' : IDL.Opt(Timestamp),
  'templateType' : IDL.Text,
  'retryCount' : IDL.Nat,
  'dayNumber' : IDL.Nat,
  'leadId' : LeadId,
  'repliedAt' : IDL.Opt(Timestamp),
  'channel' : IDL.Text,
  'detectedProblem' : IDL.Text,
  'senderId' : IDL.Opt(SenderIdentityId),
  'consentChecked' : IDL.Bool,
  'scheduledAt' : Timestamp,
});
export const ScraperJob = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'completedAt' : IDL.Opt(Timestamp),
  'totalFound' : IDL.Nat,
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'leadsGenerated' : IDL.Nat,
  'progress' : IDL.Nat,
  'niche' : IDL.Text,
  'processed' : IDL.Nat,
});
export const WhatsAppTemplateCategory = IDL.Variant({
  'proposal_sharing' : IDL.Null,
  'lead_outreach' : IDL.Null,
  'follow_up' : IDL.Null,
});
export const WhatsAppTemplateId = IDL.Nat;
export const WhatsAppTemplateStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'paused' : IDL.Null,
});
export const WhatsAppTemplate = IDL.Record({
  'id' : WhatsAppTemplateId,
  'status' : WhatsAppTemplateStatus,
  'body' : IDL.Text,
  'approvedAt' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'usageCount' : IDL.Nat,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'submittedAt' : IDL.Opt(IDL.Int),
  'variables' : IDL.Vec(IDL.Text),
  'category' : WhatsAppTemplateCategory,
  'replyRate' : IDL.Nat,
});
export const ProposalId = IDL.Nat;
export const GrowthReportId = IDL.Nat;
export const WeeklyAction = IDL.Record({
  'action' : IDL.Text,
  'estimatedImpact' : IDL.Text,
  'rationale' : IDL.Text,
  'category' : IDL.Variant({
    'local_seo' : IDL.Null,
    'run_offer' : IDL.Null,
    'collect_reviews' : IDL.Null,
    'upsell' : IDL.Null,
    'launch_ad' : IDL.Null,
    'post_content' : IDL.Null,
  }),
});
export const GrowthReport = IDL.Record({
  'id' : GrowthReportId,
  'clientId' : IDL.Nat,
  'revenueStrategies' : IDL.Vec(IDL.Text),
  'nextActions' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'leadsGenerated' : IDL.Nat,
  'conversionRate' : IDL.Nat,
  'revenueImpact' : IDL.Nat,
  'monthOf' : IDL.Text,
  'marketingSuggestions' : IDL.Vec(IDL.Text),
  'weeklyActions' : IDL.Vec(WeeklyAction),
  'reportNarrative' : IDL.Text,
  'weekOf' : IDL.Text,
});
export const CreateProposalInput = IDL.Record({
  'businessName' : IDL.Text,
  'leadId' : LeadId,
  'niche' : IDL.Text,
});
export const Proposal = IDL.Record({
  'id' : ProposalId,
  'generatedAt' : Timestamp,
  'seoStrategy' : IDL.Text,
  'businessName' : IDL.Text,
  'leadId' : LeadId,
  'niche' : IDL.Text,
  'websiteStrategy' : IDL.Text,
  'adsStrategy' : IDL.Text,
  'pricingBreakdown' : IDL.Text,
});
export const ConsentLogId = IDL.Nat;
export const ConsentType = IDL.Variant({
  'reply_first' : IDL.Null,
  'form_submission' : IDL.Null,
  'manual_override' : IDL.Null,
  'qr_optin' : IDL.Null,
});
export const ConsentLog = IDL.Record({
  'id' : ConsentLogId,
  'status' : ConsentStatus,
  'messageTemplate' : IDL.Text,
  'userId' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'consentType' : ConsentType,
});
export const DeliverabilityStatId = IDL.Nat;
export const DeliveryStats = IDL.Record({
  'id' : DeliverabilityStatId,
  'date' : IDL.Text,
  'optOutCount' : IDL.Nat,
  'blockedCount' : IDL.Nat,
  'deliveredCount' : IDL.Nat,
  'identityId' : SenderIdentityId,
  'bouncedCount' : IDL.Nat,
  'repliedCount' : IDL.Nat,
});
export const GA4CredentialStatus = IDL.Record({
  'lastUpdated' : IDL.Opt(IDL.Int),
  'propertyId' : IDL.Opt(IDL.Text),
  'isConfigured' : IDL.Bool,
});
export const GA4Dashboard = IDL.Record({
  'topPages' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
  'trafficSources' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
  'isLive' : IDL.Bool,
  'avgBounceRate' : IDL.Float64,
  'conversions' : IDL.Int,
  'totalUsers' : IDL.Int,
  'totalSessions' : IDL.Int,
});
export const GamificationState = IDL.Record({
  'creditsEarned' : IDL.Nat,
  'totalActions' : IDL.Nat,
  'currentMilestone' : IDL.Nat,
  'lastActionDate' : IDL.Text,
  'dailyStreak' : IDL.Nat,
  'unlockedFeatures' : IDL.Vec(IDL.Text),
});
export const ImportId = IDL.Nat;
export const ImportRecord = IDL.Record({
  'id' : ImportId,
  'userId' : IDL.Text,
  'duplicateCount' : IDL.Nat,
  'totalRows' : IDL.Nat,
  'filename' : IDL.Text,
  'importedCount' : IDL.Nat,
  'validCount' : IDL.Nat,
  'timestamp' : Timestamp,
  'invalidCount' : IDL.Nat,
});
export const SubscriptionPlan = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'starter' : IDL.Null,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'canceled' : IDL.Null,
  'inactive' : IDL.Null,
  'pastDue' : IDL.Null,
  'trialing' : IDL.Null,
});
export const UserSubscription = IDL.Record({
  'plan' : SubscriptionPlan,
  'leadCredits' : IDL.Nat,
  'subscriptionStatus' : SubscriptionStatus,
  'stripeCustomerId' : IDL.Text,
});
export const OnboardingPrefs = IDL.Record({
  'city' : IDL.Text,
  'targetBudget' : IDL.Nat,
  'niche' : IDL.Text,
  'completedOnboarding' : IDL.Bool,
});
export const TemplateId = IDL.Nat;
export const TemplateSections = IDL.Record({
  'cta' : IDL.Text,
  'features' : IDL.Text,
  'hero' : IDL.Text,
  'testimonials' : IDL.Text,
  'footer' : IDL.Text,
});
export const WebsiteTemplate = IDL.Record({
  'id' : TemplateId,
  'clientId' : ClientId,
  'templateId' : IDL.Text,
  'templateName' : IDL.Text,
  'sections' : TemplateSections,
  'lastSaved' : Timestamp,
});
export const ImportRowStatus = IDL.Variant({
  'valid' : IDL.Null,
  'invalid' : IDL.Null,
  'duplicate' : IDL.Null,
});
export const ImportRowResult = IDL.Record({
  'status' : ImportRowStatus,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'rowIndex' : IDL.Nat,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
  'reason' : IDL.Text,
});
export const SeoAuditId = IDL.Nat;
export const SeoAuditItem = IDL.Record({
  'status' : IDL.Variant({
    'warning' : IDL.Null,
    'fail' : IDL.Null,
    'pass' : IDL.Null,
  }),
  'suggestion' : IDL.Text,
  'itemLabel' : IDL.Text,
});
export const SeoAuditRecord = IDL.Record({
  'id' : SeoAuditId,
  'url' : IDL.Text,
  'metaScore' : IDL.Nat,
  'blogOutlines' : IDL.Vec(
    IDL.Record({
      'title' : IDL.Text,
      'wordCount' : IDL.Nat,
      'outline' : IDL.Vec(IDL.Text),
      'targetKeyword' : IDL.Text,
    })
  ),
  'createdAt' : IDL.Int,
  'headingScore' : IDL.Nat,
  'pageSpeedScore' : IDL.Nat,
  'titleScore' : IDL.Nat,
  'mobileFriendlyScore' : IDL.Nat,
  'items' : IDL.Vec(SeoAuditItem),
  'keywordDensityScore' : IDL.Nat,
});
export const SaveTemplateInput = IDL.Record({
  'clientId' : ClientId,
  'templateId' : IDL.Text,
  'templateName' : IDL.Text,
  'sections' : TemplateSections,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateClientMetricsInput = IDL.Record({
  'id' : ClientId,
  'metrics' : ClientMetrics,
  'reportDate' : Timestamp,
});
export const UpdateLeadInput = IDL.Record({
  'id' : LeadId,
  'status' : LeadStatus,
  'city' : IDL.Text,
  'leadScore' : IDL.Nat,
  'businessName' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'industry' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addSenderIdentity' : IDL.Func([IDL.Text, SenderType], [SenderIdentity], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkOptOutStatus' : IDL.Func([LeadId], [IDL.Bool], ['query']),
  'claimMilestoneReward' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'clearGA4Credentials' : IDL.Func([], [], []),
  'completeNote' : IDL.Func([NoteId], [IDL.Bool], []),
  'completeOnboarding' : IDL.Func([], [], []),
  'createClient' : IDL.Func([CreateClientInput], [Client], []),
  'createConversionScript' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ConversionScript],
      [],
    ),
  'createGrowthSuggestion' : IDL.Func(
      [CreateSuggestionInput],
      [GrowthSuggestion],
      [],
    ),
  'createLandingPage' : IDL.Func(
      [LandingPageNiche, IDL.Text, IDL.Text, IDL.Text],
      [LandingPage],
      [],
    ),
  'createLead' : IDL.Func([CreateLeadInput], [Lead], []),
  'createNote' : IDL.Func([CreateNoteInput], [Note], []),
  'createOutreachCampaign' : IDL.Func(
      [CreateOutreachCampaignInput],
      [OutreachCampaign],
      [],
    ),
  'createOutreachMessage' : IDL.Func(
      [CreateOutreachMessageInput],
      [OutreachMessage],
      [],
    ),
  'createScraperJob' : IDL.Func([IDL.Text, IDL.Text], [ScraperJob], []),
  'createWhatsAppTemplate' : IDL.Func(
      [IDL.Text, WhatsAppTemplateCategory, IDL.Text, IDL.Vec(IDL.Text)],
      [WhatsAppTemplate],
      [],
    ),
  'deleteClient' : IDL.Func([ClientId], [IDL.Bool], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
  'deleteProposal' : IDL.Func([ProposalId], [IDL.Bool], []),
  'dismissSuggestion' : IDL.Func([SuggestionId], [IDL.Bool], []),
  'generateGrowthReport' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [GrowthReport],
      [],
    ),
  'generateProposal' : IDL.Func([CreateProposalInput], [Proposal], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaignsByLead' : IDL.Func(
      [LeadId],
      [IDL.Vec(OutreachCampaign)],
      ['query'],
    ),
  'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
  'getConsentLogs' : IDL.Func([], [IDL.Vec(ConsentLog)], ['query']),
  'getDeliverabilityMetrics' : IDL.Func(
      [SenderIdentityId],
      [IDL.Vec(DeliveryStats)],
      ['query'],
    ),
  'getGA4CredentialStatus' : IDL.Func([], [GA4CredentialStatus], ['query']),
  'getGA4Dashboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : GA4Dashboard, 'err' : IDL.Text })],
      [],
    ),
  'getGamificationState' : IDL.Func([], [GamificationState], ['query']),
  'getImportHistory' : IDL.Func([], [IDL.Vec(ImportRecord)], ['query']),
  'getLandingPage' : IDL.Func(
      [LandingPageId],
      [IDL.Opt(LandingPage)],
      ['query'],
    ),
  'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Opt(UserSubscription)], ['query']),
  'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'getOnboardingPrefs' : IDL.Func([], [IDL.Opt(OnboardingPrefs)], ['query']),
  'getOutreachMessagesByLead' : IDL.Func(
      [LeadId],
      [IDL.Vec(OutreachMessage)],
      ['query'],
    ),
  'getProposal' : IDL.Func([ProposalId], [IDL.Opt(Proposal)], ['query']),
  'getScraperJob' : IDL.Func([IDL.Nat], [IDL.Opt(ScraperJob)], ['query']),
  'getSenderIdentities' : IDL.Func([], [IDL.Vec(SenderIdentity)], ['query']),
  'getSubscriptionByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserSubscription)],
      [],
    ),
  'getWebsiteTemplate' : IDL.Func(
      [ClientId],
      [IDL.Opt(WebsiteTemplate)],
      ['query'],
    ),
  'importCSVLeads' : IDL.Func(
      [IDL.Vec(ImportRowResult), IDL.Text, IDL.Text],
      [ImportRecord],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllCampaigns' : IDL.Func([], [IDL.Vec(OutreachCampaign)], ['query']),
  'listAllOutreachMessages' : IDL.Func(
      [],
      [IDL.Vec(OutreachMessage)],
      ['query'],
    ),
  'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'listConversionScripts' : IDL.Func(
      [],
      [IDL.Vec(ConversionScript)],
      ['query'],
    ),
  'listGrowthReports' : IDL.Func([IDL.Nat], [IDL.Vec(GrowthReport)], ['query']),
  'listGrowthSuggestions' : IDL.Func(
      [ClientId],
      [IDL.Vec(GrowthSuggestion)],
      ['query'],
    ),
  'listLandingPages' : IDL.Func([], [IDL.Vec(LandingPage)], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'listLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
  'listNotesByLead' : IDL.Func([LeadId], [IDL.Vec(Note)], ['query']),
  'listProposalsByLead' : IDL.Func([LeadId], [IDL.Vec(Proposal)], ['query']),
  'listScraperJobs' : IDL.Func([], [IDL.Vec(ScraperJob)], ['query']),
  'listSeoAudits' : IDL.Func([], [IDL.Vec(SeoAuditRecord)], ['query']),
  'listWhatsAppTemplates' : IDL.Func(
      [],
      [IDL.Vec(WhatsAppTemplate)],
      ['query'],
    ),
  'markSuggestionImplemented' : IDL.Func([SuggestionId], [IDL.Bool], []),
  'moveLead' : IDL.Func([LeadId, LeadStatus], [IDL.Bool], []),
  'publishLandingPage' : IDL.Func([LandingPageId], [IDL.Bool], []),
  'recordConsentLog' : IDL.Func(
      [IDL.Text, IDL.Text, ConsentType, IDL.Text, IDL.Text, IDL.Text],
      [ConsentLogId],
      [],
    ),
  'recordDailyAction' : IDL.Func([IDL.Text], [GamificationState], []),
  'recordDeliveryStats' : IDL.Func(
      [SenderIdentityId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [DeliverabilityStatId],
      [],
    ),
  'runSeoAudit' : IDL.Func([IDL.Text], [SeoAuditRecord], []),
  'saveOnboardingPrefs' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'saveWebsiteTemplate' : IDL.Func([SaveTemplateInput], [WebsiteTemplate], []),
  'setGA4Credentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitTemplateForApproval' : IDL.Func([WhatsAppTemplateId], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformGA4' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCampaignStats' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [OutreachCampaign],
      [],
    ),
  'updateClientMetrics' : IDL.Func([UpdateClientMetricsInput], [IDL.Bool], []),
  'updateConsentStatus' : IDL.Func(
      [ConsentLogId, ConsentStatus],
      [IDL.Bool],
      [],
    ),
  'updateLead' : IDL.Func([UpdateLeadInput], [IDL.Bool], []),
  'updateOutreachMessageStatus' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(Timestamp)],
      [OutreachMessage],
      [],
    ),
  'updateScraperJobProgress' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [ScraperJob],
      [],
    ),
  'updateSenderReputation' : IDL.Func(
      [SenderIdentityId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateTemplateApprovalStatus' : IDL.Func(
      [WhatsAppTemplateId, WhatsAppTemplateStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'upsertMySubscription' : IDL.Func([UserSubscription], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SenderType = IDL.Variant({
    'whatsapp' : IDL.Null,
    'email_domain' : IDL.Null,
  });
  const SenderIdentityId = IDL.Nat;
  const WarmupPhase = IDL.Variant({
    'unlimited' : IDL.Null,
    'phase1' : IDL.Null,
    'phase2' : IDL.Null,
    'phase3' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const SenderIdentity = IDL.Record({
    'id' : SenderIdentityId,
    'reputationScore' : IDL.Nat,
    'warmupPhase' : WarmupPhase,
    'createdAt' : Timestamp,
    'totalReplied' : IDL.Nat,
    'totalSent' : IDL.Nat,
    'totalDelivered' : IDL.Nat,
    'totalBounced' : IDL.Nat,
    'blockedCount' : IDL.Nat,
    'senderType' : SenderType,
    'identifier' : IDL.Text,
    'totalOptOut' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeadId = IDL.Nat;
  const NoteId = IDL.Nat;
  const CreateClientInput = IDL.Record({
    'businessName' : IDL.Text,
    'leadId' : LeadId,
    'startDate' : Timestamp,
  });
  const ClientId = IDL.Nat;
  const ClientMetrics = IDL.Record({
    'revenue' : IDL.Float64,
    'leads' : IDL.Nat,
    'traffic' : IDL.Nat,
    'conversions' : IDL.Nat,
  });
  const Client = IDL.Record({
    'id' : ClientId,
    'metrics' : ClientMetrics,
    'businessName' : IDL.Text,
    'reportDate' : Timestamp,
    'leadId' : LeadId,
    'startDate' : Timestamp,
  });
  const ConversionScriptId = IDL.Nat;
  const ScriptType = IDL.Variant({
    'chat_suggestion' : IDL.Null,
    'call_script' : IDL.Null,
    'email_sequence' : IDL.Null,
  });
  const ConversionScript = IDL.Record({
    'id' : ConversionScriptId,
    'serviceType' : IDL.Text,
    'discoveryQuestions' : IDL.Vec(IDL.Text),
    'opener' : IDL.Text,
    'scriptType' : ScriptType,
    'createdAt' : IDL.Int,
    'painPoint' : IDL.Text,
    'budgetTier' : IDL.Text,
    'valueProp' : IDL.Text,
    'closingTalk' : IDL.Text,
    'objectionHandlers' : IDL.Vec(
      IDL.Record({
        'softResponse' : IDL.Text,
        'directResponse' : IDL.Text,
        'objection' : IDL.Text,
      })
    ),
  });
  const SuggestionPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const CreateSuggestionInput = IDL.Record({
    'title' : IDL.Text,
    'clientId' : ClientId,
    'estimatedImpact' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priority' : SuggestionPriority,
    'weekOf' : Timestamp,
  });
  const SuggestionId = IDL.Nat;
  const GrowthSuggestion = IDL.Record({
    'id' : SuggestionId,
    'title' : IDL.Text,
    'clientId' : ClientId,
    'estimatedImpact' : IDL.Text,
    'description' : IDL.Text,
    'implemented' : IDL.Bool,
    'category' : IDL.Text,
    'priority' : SuggestionPriority,
    'dismissed' : IDL.Bool,
    'weekOf' : Timestamp,
  });
  const LandingPageNiche = IDL.Variant({
    'gym' : IDL.Null,
    'plumber' : IDL.Null,
    'cafe' : IDL.Null,
    'education' : IDL.Null,
    'agency' : IDL.Null,
    'salon' : IDL.Null,
    'real_estate' : IDL.Null,
    'restaurant' : IDL.Null,
    'medical' : IDL.Null,
  });
  const LandingPageId = IDL.Nat;
  const LandingPageStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
    'archived' : IDL.Null,
  });
  const LandingPageSection = IDL.Record({
    'hero' : IDL.Text,
    'ctaText' : IDL.Text,
    'painPoints' : IDL.Vec(IDL.Text),
    'formTitle' : IDL.Text,
    'beforeAfter' : IDL.Record({ 'after' : IDL.Text, 'before' : IDL.Text }),
    'testimonials' : IDL.Vec(
      IDL.Record({
        'name' : IDL.Text,
        'quote' : IDL.Text,
        'business' : IDL.Text,
      })
    ),
    'subheadline' : IDL.Text,
  });
  const LandingPage = IDL.Record({
    'id' : LandingPageId,
    'status' : LandingPageStatus,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'serviceDescription' : IDL.Text,
    'publishedAt' : IDL.Opt(IDL.Int),
    'estimatedConversionRate' : IDL.Nat,
    'estimatedLeadScore' : IDL.Nat,
    'targetBudget' : IDL.Text,
    'niche' : LandingPageNiche,
    'leadsCaptured' : IDL.Nat,
    'sections' : LandingPageSection,
  });
  const CreateLeadInput = IDL.Record({
    'city' : IDL.Text,
    'leadScore' : IDL.Nat,
    'businessName' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'industry' : IDL.Text,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'proposal' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const LeadScoreBreakdown = IDL.Record({
    'seo' : IDL.Nat,
    'reviews' : IDL.Nat,
    'social' : IDL.Nat,
    'domainAge' : IDL.Nat,
    'website' : IDL.Nat,
  });
  const ConsentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'granted' : IDL.Null,
    'withdrawn' : IDL.Null,
  });
  const PriorityTag = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : LeadId,
    'status' : LeadStatus,
    'scoreBreakdown' : IDL.Opt(LeadScoreBreakdown),
    'consentStatus' : IDL.Opt(ConsentStatus),
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'leadScore' : IDL.Nat,
    'businessName' : IDL.Text,
    'website' : IDL.Text,
    'attemptCount' : IDL.Nat,
    'updatedAt' : Timestamp,
    'referredBy' : IDL.Opt(LeadId),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'leadSource' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'optedOut' : IDL.Bool,
    'priorityTag' : IDL.Opt(PriorityTag),
    'industry' : IDL.Text,
  });
  const NoteType = IDL.Variant({ 'reminder' : IDL.Null, 'note' : IDL.Null });
  const CreateNoteInput = IDL.Record({
    'content' : IDL.Text,
    'dueDate' : IDL.Opt(Timestamp),
    'noteType' : NoteType,
    'leadId' : LeadId,
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Timestamp),
    'noteType' : NoteType,
    'leadId' : LeadId,
  });
  const CreateOutreachCampaignInput = IDL.Record({
    'businessName' : IDL.Text,
    'channels' : IDL.Vec(IDL.Text),
    'leadId' : LeadId,
  });
  const OutreachCampaign = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'completedAt' : IDL.Opt(Timestamp),
    'startedAt' : Timestamp,
    'businessName' : IDL.Text,
    'totalMessages' : IDL.Nat,
    'channels' : IDL.Vec(IDL.Text),
    'leadId' : LeadId,
    'deliveredCount' : IDL.Nat,
    'repliedCount' : IDL.Nat,
  });
  const CreateOutreachMessageInput = IDL.Record({
    'personalizedMessage' : IDL.Text,
    'businessName' : IDL.Text,
    'templateType' : IDL.Text,
    'dayNumber' : IDL.Nat,
    'leadId' : LeadId,
    'channel' : IDL.Text,
    'detectedProblem' : IDL.Text,
    'scheduledAt' : Timestamp,
  });
  const OutreachMessage = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'deliveredAt' : IDL.Opt(Timestamp),
    'personalizedMessage' : IDL.Text,
    'bounceReason' : IDL.Text,
    'businessName' : IDL.Text,
    'sentAt' : IDL.Opt(Timestamp),
    'templateType' : IDL.Text,
    'retryCount' : IDL.Nat,
    'dayNumber' : IDL.Nat,
    'leadId' : LeadId,
    'repliedAt' : IDL.Opt(Timestamp),
    'channel' : IDL.Text,
    'detectedProblem' : IDL.Text,
    'senderId' : IDL.Opt(SenderIdentityId),
    'consentChecked' : IDL.Bool,
    'scheduledAt' : Timestamp,
  });
  const ScraperJob = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'completedAt' : IDL.Opt(Timestamp),
    'totalFound' : IDL.Nat,
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'leadsGenerated' : IDL.Nat,
    'progress' : IDL.Nat,
    'niche' : IDL.Text,
    'processed' : IDL.Nat,
  });
  const WhatsAppTemplateCategory = IDL.Variant({
    'proposal_sharing' : IDL.Null,
    'lead_outreach' : IDL.Null,
    'follow_up' : IDL.Null,
  });
  const WhatsAppTemplateId = IDL.Nat;
  const WhatsAppTemplateStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'paused' : IDL.Null,
  });
  const WhatsAppTemplate = IDL.Record({
    'id' : WhatsAppTemplateId,
    'status' : WhatsAppTemplateStatus,
    'body' : IDL.Text,
    'approvedAt' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'usageCount' : IDL.Nat,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'submittedAt' : IDL.Opt(IDL.Int),
    'variables' : IDL.Vec(IDL.Text),
    'category' : WhatsAppTemplateCategory,
    'replyRate' : IDL.Nat,
  });
  const ProposalId = IDL.Nat;
  const GrowthReportId = IDL.Nat;
  const WeeklyAction = IDL.Record({
    'action' : IDL.Text,
    'estimatedImpact' : IDL.Text,
    'rationale' : IDL.Text,
    'category' : IDL.Variant({
      'local_seo' : IDL.Null,
      'run_offer' : IDL.Null,
      'collect_reviews' : IDL.Null,
      'upsell' : IDL.Null,
      'launch_ad' : IDL.Null,
      'post_content' : IDL.Null,
    }),
  });
  const GrowthReport = IDL.Record({
    'id' : GrowthReportId,
    'clientId' : IDL.Nat,
    'revenueStrategies' : IDL.Vec(IDL.Text),
    'nextActions' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'leadsGenerated' : IDL.Nat,
    'conversionRate' : IDL.Nat,
    'revenueImpact' : IDL.Nat,
    'monthOf' : IDL.Text,
    'marketingSuggestions' : IDL.Vec(IDL.Text),
    'weeklyActions' : IDL.Vec(WeeklyAction),
    'reportNarrative' : IDL.Text,
    'weekOf' : IDL.Text,
  });
  const CreateProposalInput = IDL.Record({
    'businessName' : IDL.Text,
    'leadId' : LeadId,
    'niche' : IDL.Text,
  });
  const Proposal = IDL.Record({
    'id' : ProposalId,
    'generatedAt' : Timestamp,
    'seoStrategy' : IDL.Text,
    'businessName' : IDL.Text,
    'leadId' : LeadId,
    'niche' : IDL.Text,
    'websiteStrategy' : IDL.Text,
    'adsStrategy' : IDL.Text,
    'pricingBreakdown' : IDL.Text,
  });
  const ConsentLogId = IDL.Nat;
  const ConsentType = IDL.Variant({
    'reply_first' : IDL.Null,
    'form_submission' : IDL.Null,
    'manual_override' : IDL.Null,
    'qr_optin' : IDL.Null,
  });
  const ConsentLog = IDL.Record({
    'id' : ConsentLogId,
    'status' : ConsentStatus,
    'messageTemplate' : IDL.Text,
    'userId' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'consentType' : ConsentType,
  });
  const DeliverabilityStatId = IDL.Nat;
  const DeliveryStats = IDL.Record({
    'id' : DeliverabilityStatId,
    'date' : IDL.Text,
    'optOutCount' : IDL.Nat,
    'blockedCount' : IDL.Nat,
    'deliveredCount' : IDL.Nat,
    'identityId' : SenderIdentityId,
    'bouncedCount' : IDL.Nat,
    'repliedCount' : IDL.Nat,
  });
  const GA4CredentialStatus = IDL.Record({
    'lastUpdated' : IDL.Opt(IDL.Int),
    'propertyId' : IDL.Opt(IDL.Text),
    'isConfigured' : IDL.Bool,
  });
  const GA4Dashboard = IDL.Record({
    'topPages' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
    'trafficSources' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
    'isLive' : IDL.Bool,
    'avgBounceRate' : IDL.Float64,
    'conversions' : IDL.Int,
    'totalUsers' : IDL.Int,
    'totalSessions' : IDL.Int,
  });
  const GamificationState = IDL.Record({
    'creditsEarned' : IDL.Nat,
    'totalActions' : IDL.Nat,
    'currentMilestone' : IDL.Nat,
    'lastActionDate' : IDL.Text,
    'dailyStreak' : IDL.Nat,
    'unlockedFeatures' : IDL.Vec(IDL.Text),
  });
  const ImportId = IDL.Nat;
  const ImportRecord = IDL.Record({
    'id' : ImportId,
    'userId' : IDL.Text,
    'duplicateCount' : IDL.Nat,
    'totalRows' : IDL.Nat,
    'filename' : IDL.Text,
    'importedCount' : IDL.Nat,
    'validCount' : IDL.Nat,
    'timestamp' : Timestamp,
    'invalidCount' : IDL.Nat,
  });
  const SubscriptionPlan = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'starter' : IDL.Null,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'canceled' : IDL.Null,
    'inactive' : IDL.Null,
    'pastDue' : IDL.Null,
    'trialing' : IDL.Null,
  });
  const UserSubscription = IDL.Record({
    'plan' : SubscriptionPlan,
    'leadCredits' : IDL.Nat,
    'subscriptionStatus' : SubscriptionStatus,
    'stripeCustomerId' : IDL.Text,
  });
  const OnboardingPrefs = IDL.Record({
    'city' : IDL.Text,
    'targetBudget' : IDL.Nat,
    'niche' : IDL.Text,
    'completedOnboarding' : IDL.Bool,
  });
  const TemplateId = IDL.Nat;
  const TemplateSections = IDL.Record({
    'cta' : IDL.Text,
    'features' : IDL.Text,
    'hero' : IDL.Text,
    'testimonials' : IDL.Text,
    'footer' : IDL.Text,
  });
  const WebsiteTemplate = IDL.Record({
    'id' : TemplateId,
    'clientId' : ClientId,
    'templateId' : IDL.Text,
    'templateName' : IDL.Text,
    'sections' : TemplateSections,
    'lastSaved' : Timestamp,
  });
  const ImportRowStatus = IDL.Variant({
    'valid' : IDL.Null,
    'invalid' : IDL.Null,
    'duplicate' : IDL.Null,
  });
  const ImportRowResult = IDL.Record({
    'status' : ImportRowStatus,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'rowIndex' : IDL.Nat,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
    'reason' : IDL.Text,
  });
  const SeoAuditId = IDL.Nat;
  const SeoAuditItem = IDL.Record({
    'status' : IDL.Variant({
      'warning' : IDL.Null,
      'fail' : IDL.Null,
      'pass' : IDL.Null,
    }),
    'suggestion' : IDL.Text,
    'itemLabel' : IDL.Text,
  });
  const SeoAuditRecord = IDL.Record({
    'id' : SeoAuditId,
    'url' : IDL.Text,
    'metaScore' : IDL.Nat,
    'blogOutlines' : IDL.Vec(
      IDL.Record({
        'title' : IDL.Text,
        'wordCount' : IDL.Nat,
        'outline' : IDL.Vec(IDL.Text),
        'targetKeyword' : IDL.Text,
      })
    ),
    'createdAt' : IDL.Int,
    'headingScore' : IDL.Nat,
    'pageSpeedScore' : IDL.Nat,
    'titleScore' : IDL.Nat,
    'mobileFriendlyScore' : IDL.Nat,
    'items' : IDL.Vec(SeoAuditItem),
    'keywordDensityScore' : IDL.Nat,
  });
  const SaveTemplateInput = IDL.Record({
    'clientId' : ClientId,
    'templateId' : IDL.Text,
    'templateName' : IDL.Text,
    'sections' : TemplateSections,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateClientMetricsInput = IDL.Record({
    'id' : ClientId,
    'metrics' : ClientMetrics,
    'reportDate' : Timestamp,
  });
  const UpdateLeadInput = IDL.Record({
    'id' : LeadId,
    'status' : LeadStatus,
    'city' : IDL.Text,
    'leadScore' : IDL.Nat,
    'businessName' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'industry' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addSenderIdentity' : IDL.Func(
        [IDL.Text, SenderType],
        [SenderIdentity],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkOptOutStatus' : IDL.Func([LeadId], [IDL.Bool], ['query']),
    'claimMilestoneReward' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'clearGA4Credentials' : IDL.Func([], [], []),
    'completeNote' : IDL.Func([NoteId], [IDL.Bool], []),
    'completeOnboarding' : IDL.Func([], [], []),
    'createClient' : IDL.Func([CreateClientInput], [Client], []),
    'createConversionScript' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ConversionScript],
        [],
      ),
    'createGrowthSuggestion' : IDL.Func(
        [CreateSuggestionInput],
        [GrowthSuggestion],
        [],
      ),
    'createLandingPage' : IDL.Func(
        [LandingPageNiche, IDL.Text, IDL.Text, IDL.Text],
        [LandingPage],
        [],
      ),
    'createLead' : IDL.Func([CreateLeadInput], [Lead], []),
    'createNote' : IDL.Func([CreateNoteInput], [Note], []),
    'createOutreachCampaign' : IDL.Func(
        [CreateOutreachCampaignInput],
        [OutreachCampaign],
        [],
      ),
    'createOutreachMessage' : IDL.Func(
        [CreateOutreachMessageInput],
        [OutreachMessage],
        [],
      ),
    'createScraperJob' : IDL.Func([IDL.Text, IDL.Text], [ScraperJob], []),
    'createWhatsAppTemplate' : IDL.Func(
        [IDL.Text, WhatsAppTemplateCategory, IDL.Text, IDL.Vec(IDL.Text)],
        [WhatsAppTemplate],
        [],
      ),
    'deleteClient' : IDL.Func([ClientId], [IDL.Bool], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
    'deleteProposal' : IDL.Func([ProposalId], [IDL.Bool], []),
    'dismissSuggestion' : IDL.Func([SuggestionId], [IDL.Bool], []),
    'generateGrowthReport' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [GrowthReport],
        [],
      ),
    'generateProposal' : IDL.Func([CreateProposalInput], [Proposal], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaignsByLead' : IDL.Func(
        [LeadId],
        [IDL.Vec(OutreachCampaign)],
        ['query'],
      ),
    'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
    'getConsentLogs' : IDL.Func([], [IDL.Vec(ConsentLog)], ['query']),
    'getDeliverabilityMetrics' : IDL.Func(
        [SenderIdentityId],
        [IDL.Vec(DeliveryStats)],
        ['query'],
      ),
    'getGA4CredentialStatus' : IDL.Func([], [GA4CredentialStatus], ['query']),
    'getGA4Dashboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : GA4Dashboard, 'err' : IDL.Text })],
        [],
      ),
    'getGamificationState' : IDL.Func([], [GamificationState], ['query']),
    'getImportHistory' : IDL.Func([], [IDL.Vec(ImportRecord)], ['query']),
    'getLandingPage' : IDL.Func(
        [LandingPageId],
        [IDL.Opt(LandingPage)],
        ['query'],
      ),
    'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
    'getMySubscription' : IDL.Func([], [IDL.Opt(UserSubscription)], ['query']),
    'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'getOnboardingPrefs' : IDL.Func([], [IDL.Opt(OnboardingPrefs)], ['query']),
    'getOutreachMessagesByLead' : IDL.Func(
        [LeadId],
        [IDL.Vec(OutreachMessage)],
        ['query'],
      ),
    'getProposal' : IDL.Func([ProposalId], [IDL.Opt(Proposal)], ['query']),
    'getScraperJob' : IDL.Func([IDL.Nat], [IDL.Opt(ScraperJob)], ['query']),
    'getSenderIdentities' : IDL.Func([], [IDL.Vec(SenderIdentity)], ['query']),
    'getSubscriptionByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserSubscription)],
        [],
      ),
    'getWebsiteTemplate' : IDL.Func(
        [ClientId],
        [IDL.Opt(WebsiteTemplate)],
        ['query'],
      ),
    'importCSVLeads' : IDL.Func(
        [IDL.Vec(ImportRowResult), IDL.Text, IDL.Text],
        [ImportRecord],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllCampaigns' : IDL.Func([], [IDL.Vec(OutreachCampaign)], ['query']),
    'listAllOutreachMessages' : IDL.Func(
        [],
        [IDL.Vec(OutreachMessage)],
        ['query'],
      ),
    'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'listConversionScripts' : IDL.Func(
        [],
        [IDL.Vec(ConversionScript)],
        ['query'],
      ),
    'listGrowthReports' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GrowthReport)],
        ['query'],
      ),
    'listGrowthSuggestions' : IDL.Func(
        [ClientId],
        [IDL.Vec(GrowthSuggestion)],
        ['query'],
      ),
    'listLandingPages' : IDL.Func([], [IDL.Vec(LandingPage)], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'listLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
    'listNotesByLead' : IDL.Func([LeadId], [IDL.Vec(Note)], ['query']),
    'listProposalsByLead' : IDL.Func([LeadId], [IDL.Vec(Proposal)], ['query']),
    'listScraperJobs' : IDL.Func([], [IDL.Vec(ScraperJob)], ['query']),
    'listSeoAudits' : IDL.Func([], [IDL.Vec(SeoAuditRecord)], ['query']),
    'listWhatsAppTemplates' : IDL.Func(
        [],
        [IDL.Vec(WhatsAppTemplate)],
        ['query'],
      ),
    'markSuggestionImplemented' : IDL.Func([SuggestionId], [IDL.Bool], []),
    'moveLead' : IDL.Func([LeadId, LeadStatus], [IDL.Bool], []),
    'publishLandingPage' : IDL.Func([LandingPageId], [IDL.Bool], []),
    'recordConsentLog' : IDL.Func(
        [IDL.Text, IDL.Text, ConsentType, IDL.Text, IDL.Text, IDL.Text],
        [ConsentLogId],
        [],
      ),
    'recordDailyAction' : IDL.Func([IDL.Text], [GamificationState], []),
    'recordDeliveryStats' : IDL.Func(
        [
          SenderIdentityId,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [DeliverabilityStatId],
        [],
      ),
    'runSeoAudit' : IDL.Func([IDL.Text], [SeoAuditRecord], []),
    'saveOnboardingPrefs' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'saveWebsiteTemplate' : IDL.Func(
        [SaveTemplateInput],
        [WebsiteTemplate],
        [],
      ),
    'setGA4Credentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitTemplateForApproval' : IDL.Func(
        [WhatsAppTemplateId],
        [IDL.Bool],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformGA4' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCampaignStats' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [OutreachCampaign],
        [],
      ),
    'updateClientMetrics' : IDL.Func(
        [UpdateClientMetricsInput],
        [IDL.Bool],
        [],
      ),
    'updateConsentStatus' : IDL.Func(
        [ConsentLogId, ConsentStatus],
        [IDL.Bool],
        [],
      ),
    'updateLead' : IDL.Func([UpdateLeadInput], [IDL.Bool], []),
    'updateOutreachMessageStatus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(Timestamp)],
        [OutreachMessage],
        [],
      ),
    'updateScraperJobProgress' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [ScraperJob],
        [],
      ),
    'updateSenderReputation' : IDL.Func(
        [SenderIdentityId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateTemplateApprovalStatus' : IDL.Func(
        [WhatsAppTemplateId, WhatsAppTemplateStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'upsertMySubscription' : IDL.Func([UserSubscription], [], []),
  });
};

export const init = ({ IDL }) => { return []; };