/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : ClientId,
  'metrics' : ClientMetrics,
  'businessName' : string,
  'reportDate' : Timestamp,
  'leadId' : LeadId,
  'startDate' : Timestamp,
}
export type ClientId = bigint;
export interface ClientMetrics {
  'revenue' : number,
  'leads' : bigint,
  'traffic' : bigint,
  'conversions' : bigint,
}
export interface ConsentLog {
  'id' : ConsentLogId,
  'status' : ConsentStatus,
  'messageTemplate' : string,
  'userId' : string,
  'email' : string,
  'notes' : string,
  'timestamp' : Timestamp,
  'phone' : string,
  'consentType' : ConsentType,
}
export type ConsentLogId = bigint;
export type ConsentStatus = { 'pending' : null } |
  { 'granted' : null } |
  { 'withdrawn' : null };
export type ConsentType = { 'reply_first' : null } |
  { 'form_submission' : null } |
  { 'manual_override' : null } |
  { 'qr_optin' : null };
export interface ConversionScript {
  'id' : ConversionScriptId,
  'serviceType' : string,
  'discoveryQuestions' : Array<string>,
  'opener' : string,
  'scriptType' : ScriptType,
  'createdAt' : bigint,
  'painPoint' : string,
  'budgetTier' : string,
  'valueProp' : string,
  'closingTalk' : string,
  'objectionHandlers' : Array<
    { 'softResponse' : string, 'directResponse' : string, 'objection' : string }
  >,
}
export type ConversionScriptId = bigint;
export interface CreateClientInput {
  'businessName' : string,
  'leadId' : LeadId,
  'startDate' : Timestamp,
}
export interface CreateLeadInput {
  'city' : string,
  'leadScore' : bigint,
  'businessName' : string,
  'website' : string,
  'address' : string,
  'notes' : string,
  'rating' : number,
  'phone' : string,
  'industry' : string,
}
export interface CreateNoteInput {
  'content' : string,
  'dueDate' : [] | [Timestamp],
  'noteType' : NoteType,
  'leadId' : LeadId,
}
export interface CreateOutreachCampaignInput {
  'businessName' : string,
  'channels' : Array<string>,
  'leadId' : LeadId,
}
export interface CreateOutreachMessageInput {
  'personalizedMessage' : string,
  'businessName' : string,
  'templateType' : string,
  'dayNumber' : bigint,
  'leadId' : LeadId,
  'channel' : string,
  'detectedProblem' : string,
  'scheduledAt' : Timestamp,
}
export interface CreateProposalInput {
  'businessName' : string,
  'leadId' : LeadId,
  'niche' : string,
}
export interface CreateSuggestionInput {
  'title' : string,
  'clientId' : ClientId,
  'estimatedImpact' : string,
  'description' : string,
  'category' : string,
  'priority' : SuggestionPriority,
  'weekOf' : Timestamp,
}
export type DeliverabilityStatId = bigint;
export interface DeliveryStats {
  'id' : DeliverabilityStatId,
  'date' : string,
  'optOutCount' : bigint,
  'blockedCount' : bigint,
  'deliveredCount' : bigint,
  'identityId' : SenderIdentityId,
  'bouncedCount' : bigint,
  'repliedCount' : bigint,
}
export interface GA4CredentialStatus {
  'lastUpdated' : [] | [bigint],
  'propertyId' : [] | [string],
  'isConfigured' : boolean,
}
export interface GA4Dashboard {
  'topPages' : Array<[string, bigint]>,
  'trafficSources' : Array<[string, bigint]>,
  'isLive' : boolean,
  'avgBounceRate' : number,
  'conversions' : bigint,
  'totalUsers' : bigint,
  'totalSessions' : bigint,
}
export interface GamificationState {
  'creditsEarned' : bigint,
  'totalActions' : bigint,
  'currentMilestone' : bigint,
  'lastActionDate' : string,
  'dailyStreak' : bigint,
  'unlockedFeatures' : Array<string>,
}
export interface GrowthReport {
  'id' : GrowthReportId,
  'clientId' : bigint,
  'revenueStrategies' : Array<string>,
  'nextActions' : Array<string>,
  'createdAt' : bigint,
  'leadsGenerated' : bigint,
  'conversionRate' : bigint,
  'revenueImpact' : bigint,
  'monthOf' : string,
  'marketingSuggestions' : Array<string>,
  'weeklyActions' : Array<WeeklyAction>,
  'reportNarrative' : string,
  'weekOf' : string,
}
export type GrowthReportId = bigint;
export interface GrowthSuggestion {
  'id' : SuggestionId,
  'title' : string,
  'clientId' : ClientId,
  'estimatedImpact' : string,
  'description' : string,
  'implemented' : boolean,
  'category' : string,
  'priority' : SuggestionPriority,
  'dismissed' : boolean,
  'weekOf' : Timestamp,
}
export type ImportId = bigint;
export interface ImportRecord {
  'id' : ImportId,
  'userId' : string,
  'duplicateCount' : bigint,
  'totalRows' : bigint,
  'filename' : string,
  'importedCount' : bigint,
  'validCount' : bigint,
  'timestamp' : Timestamp,
  'invalidCount' : bigint,
}
export interface ImportRowResult {
  'status' : ImportRowStatus,
  'city' : string,
  'name' : string,
  'rowIndex' : bigint,
  'email' : string,
  'website' : string,
  'category' : string,
  'phone' : string,
  'reason' : string,
}
export type ImportRowStatus = { 'valid' : null } |
  { 'invalid' : null } |
  { 'duplicate' : null };
export interface LandingPage {
  'id' : LandingPageId,
  'status' : LandingPageStatus,
  'city' : string,
  'createdAt' : bigint,
  'serviceDescription' : string,
  'publishedAt' : [] | [bigint],
  'estimatedConversionRate' : bigint,
  'estimatedLeadScore' : bigint,
  'targetBudget' : string,
  'niche' : LandingPageNiche,
  'leadsCaptured' : bigint,
  'sections' : LandingPageSection,
}
export type LandingPageId = bigint;
export type LandingPageNiche = { 'gym' : null } |
  { 'plumber' : null } |
  { 'cafe' : null } |
  { 'education' : null } |
  { 'agency' : null } |
  { 'salon' : null } |
  { 'real_estate' : null } |
  { 'restaurant' : null } |
  { 'medical' : null };
export interface LandingPageSection {
  'hero' : string,
  'ctaText' : string,
  'painPoints' : Array<string>,
  'formTitle' : string,
  'beforeAfter' : { 'after' : string, 'before' : string },
  'testimonials' : Array<
    { 'name' : string, 'quote' : string, 'business' : string }
  >,
  'subheadline' : string,
}
export type LandingPageStatus = { 'published' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export interface Lead {
  'id' : LeadId,
  'status' : LeadStatus,
  'scoreBreakdown' : [] | [LeadScoreBreakdown],
  'consentStatus' : [] | [ConsentStatus],
  'city' : string,
  'createdAt' : Timestamp,
  'leadScore' : bigint,
  'businessName' : string,
  'website' : string,
  'attemptCount' : bigint,
  'updatedAt' : Timestamp,
  'referredBy' : [] | [LeadId],
  'address' : string,
  'notes' : string,
  'leadSource' : string,
  'rating' : number,
  'phone' : string,
  'optedOut' : boolean,
  'priorityTag' : [] | [PriorityTag],
  'industry' : string,
}
export type LeadId = bigint;
export interface LeadScoreBreakdown {
  'seo' : bigint,
  'reviews' : bigint,
  'social' : bigint,
  'domainAge' : bigint,
  'website' : bigint,
}
export type LeadStatus = { 'new' : null } |
  { 'closed' : null } |
  { 'proposal' : null } |
  { 'contacted' : null };
export interface Note {
  'id' : NoteId,
  'content' : string,
  'createdAt' : Timestamp,
  'completed' : boolean,
  'dueDate' : [] | [Timestamp],
  'noteType' : NoteType,
  'leadId' : LeadId,
}
export type NoteId = bigint;
export type NoteType = { 'reminder' : null } |
  { 'note' : null };
export interface OnboardingPrefs {
  'city' : string,
  'targetBudget' : bigint,
  'niche' : string,
  'completedOnboarding' : boolean,
}
export interface OutreachCampaign {
  'id' : bigint,
  'status' : string,
  'completedAt' : [] | [Timestamp],
  'startedAt' : Timestamp,
  'businessName' : string,
  'totalMessages' : bigint,
  'channels' : Array<string>,
  'leadId' : LeadId,
  'deliveredCount' : bigint,
  'repliedCount' : bigint,
}
export interface OutreachMessage {
  'id' : bigint,
  'status' : string,
  'deliveredAt' : [] | [Timestamp],
  'personalizedMessage' : string,
  'bounceReason' : string,
  'businessName' : string,
  'sentAt' : [] | [Timestamp],
  'templateType' : string,
  'retryCount' : bigint,
  'dayNumber' : bigint,
  'leadId' : LeadId,
  'repliedAt' : [] | [Timestamp],
  'channel' : string,
  'detectedProblem' : string,
  'senderId' : [] | [SenderIdentityId],
  'consentChecked' : boolean,
  'scheduledAt' : Timestamp,
}
export type PriorityTag = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Proposal {
  'id' : ProposalId,
  'generatedAt' : Timestamp,
  'seoStrategy' : string,
  'businessName' : string,
  'leadId' : LeadId,
  'niche' : string,
  'websiteStrategy' : string,
  'adsStrategy' : string,
  'pricingBreakdown' : string,
}
export type ProposalId = bigint;
export interface SaveTemplateInput {
  'clientId' : ClientId,
  'templateId' : string,
  'templateName' : string,
  'sections' : TemplateSections,
}
export interface ScraperJob {
  'id' : bigint,
  'status' : string,
  'completedAt' : [] | [Timestamp],
  'totalFound' : bigint,
  'city' : string,
  'createdAt' : Timestamp,
  'leadsGenerated' : bigint,
  'progress' : bigint,
  'niche' : string,
  'processed' : bigint,
}
export type ScriptType = { 'chat_suggestion' : null } |
  { 'call_script' : null } |
  { 'email_sequence' : null };
export interface SenderIdentity {
  'id' : SenderIdentityId,
  'reputationScore' : bigint,
  'warmupPhase' : WarmupPhase,
  'createdAt' : Timestamp,
  'totalReplied' : bigint,
  'totalSent' : bigint,
  'totalDelivered' : bigint,
  'totalBounced' : bigint,
  'blockedCount' : bigint,
  'senderType' : SenderType,
  'identifier' : string,
  'totalOptOut' : bigint,
}
export type SenderIdentityId = bigint;
export type SenderType = { 'whatsapp' : null } |
  { 'email_domain' : null };
export type SeoAuditId = bigint;
export interface SeoAuditItem {
  'status' : { 'warning' : null } |
    { 'fail' : null } |
    { 'pass' : null },
  'suggestion' : string,
  'itemLabel' : string,
}
export interface SeoAuditRecord {
  'id' : SeoAuditId,
  'url' : string,
  'metaScore' : bigint,
  'blogOutlines' : Array<
    {
      'title' : string,
      'wordCount' : bigint,
      'outline' : Array<string>,
      'targetKeyword' : string,
    }
  >,
  'createdAt' : bigint,
  'headingScore' : bigint,
  'pageSpeedScore' : bigint,
  'titleScore' : bigint,
  'mobileFriendlyScore' : bigint,
  'items' : Array<SeoAuditItem>,
  'keywordDensityScore' : bigint,
}
export type SubscriptionPlan = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'starter' : null };
export type SubscriptionStatus = { 'active' : null } |
  { 'canceled' : null } |
  { 'inactive' : null } |
  { 'pastDue' : null } |
  { 'trialing' : null };
export type SuggestionId = bigint;
export type SuggestionPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TemplateId = bigint;
export interface TemplateSections {
  'cta' : string,
  'features' : string,
  'hero' : string,
  'testimonials' : string,
  'footer' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateClientMetricsInput {
  'id' : ClientId,
  'metrics' : ClientMetrics,
  'reportDate' : Timestamp,
}
export interface UpdateLeadInput {
  'id' : LeadId,
  'status' : LeadStatus,
  'city' : string,
  'leadScore' : bigint,
  'businessName' : string,
  'website' : string,
  'address' : string,
  'notes' : string,
  'rating' : number,
  'phone' : string,
  'industry' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSubscription {
  'plan' : SubscriptionPlan,
  'leadCredits' : bigint,
  'subscriptionStatus' : SubscriptionStatus,
  'stripeCustomerId' : string,
}
export type WarmupPhase = { 'unlimited' : null } |
  { 'phase1' : null } |
  { 'phase2' : null } |
  { 'phase3' : null };
export interface WebsiteTemplate {
  'id' : TemplateId,
  'clientId' : ClientId,
  'templateId' : string,
  'templateName' : string,
  'sections' : TemplateSections,
  'lastSaved' : Timestamp,
}
export interface WeeklyAction {
  'action' : string,
  'estimatedImpact' : string,
  'rationale' : string,
  'category' : { 'local_seo' : null } |
    { 'run_offer' : null } |
    { 'collect_reviews' : null } |
    { 'upsell' : null } |
    { 'launch_ad' : null } |
    { 'post_content' : null },
}
export interface WhatsAppTemplate {
  'id' : WhatsAppTemplateId,
  'status' : WhatsAppTemplateStatus,
  'body' : string,
  'approvedAt' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'usageCount' : bigint,
  'rejectionReason' : [] | [string],
  'submittedAt' : [] | [bigint],
  'variables' : Array<string>,
  'category' : WhatsAppTemplateCategory,
  'replyRate' : bigint,
}
export type WhatsAppTemplateCategory = { 'proposal_sharing' : null } |
  { 'lead_outreach' : null } |
  { 'follow_up' : null };
export type WhatsAppTemplateId = bigint;
export type WhatsAppTemplateStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'paused' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addSenderIdentity' : ActorMethod<[string, SenderType], SenderIdentity>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkOptOutStatus' : ActorMethod<[LeadId], boolean>,
  'claimMilestoneReward' : ActorMethod<[bigint], boolean>,
  'clearGA4Credentials' : ActorMethod<[], undefined>,
  'completeNote' : ActorMethod<[NoteId], boolean>,
  'completeOnboarding' : ActorMethod<[], undefined>,
  'createClient' : ActorMethod<[CreateClientInput], Client>,
  'createConversionScript' : ActorMethod<
    [string, string, string],
    ConversionScript
  >,
  'createGrowthSuggestion' : ActorMethod<
    [CreateSuggestionInput],
    GrowthSuggestion
  >,
  'createLandingPage' : ActorMethod<
    [LandingPageNiche, string, string, string],
    LandingPage
  >,
  'createLead' : ActorMethod<[CreateLeadInput], Lead>,
  'createNote' : ActorMethod<[CreateNoteInput], Note>,
  'createOutreachCampaign' : ActorMethod<
    [CreateOutreachCampaignInput],
    OutreachCampaign
  >,
  'createOutreachMessage' : ActorMethod<
    [CreateOutreachMessageInput],
    OutreachMessage
  >,
  'createScraperJob' : ActorMethod<[string, string], ScraperJob>,
  'createWhatsAppTemplate' : ActorMethod<
    [string, WhatsAppTemplateCategory, string, Array<string>],
    WhatsAppTemplate
  >,
  'deleteClient' : ActorMethod<[ClientId], boolean>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'deleteNote' : ActorMethod<[NoteId], boolean>,
  'deleteProposal' : ActorMethod<[ProposalId], boolean>,
  'dismissSuggestion' : ActorMethod<[SuggestionId], boolean>,
  'generateGrowthReport' : ActorMethod<
    [bigint, string, string, bigint, bigint, bigint],
    GrowthReport
  >,
  'generateProposal' : ActorMethod<[CreateProposalInput], Proposal>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaignsByLead' : ActorMethod<[LeadId], Array<OutreachCampaign>>,
  'getClient' : ActorMethod<[ClientId], [] | [Client]>,
  'getConsentLogs' : ActorMethod<[], Array<ConsentLog>>,
  'getDeliverabilityMetrics' : ActorMethod<
    [SenderIdentityId],
    Array<DeliveryStats>
  >,
  'getGA4CredentialStatus' : ActorMethod<[], GA4CredentialStatus>,
  'getGA4Dashboard' : ActorMethod<
    [bigint],
    { 'ok' : GA4Dashboard } |
      { 'err' : string }
  >,
  'getGamificationState' : ActorMethod<[], GamificationState>,
  'getImportHistory' : ActorMethod<[], Array<ImportRecord>>,
  'getLandingPage' : ActorMethod<[LandingPageId], [] | [LandingPage]>,
  'getLead' : ActorMethod<[LeadId], [] | [Lead]>,
  'getMySubscription' : ActorMethod<[], [] | [UserSubscription]>,
  'getNote' : ActorMethod<[NoteId], [] | [Note]>,
  'getOnboardingPrefs' : ActorMethod<[], [] | [OnboardingPrefs]>,
  'getOutreachMessagesByLead' : ActorMethod<[LeadId], Array<OutreachMessage>>,
  'getProposal' : ActorMethod<[ProposalId], [] | [Proposal]>,
  'getScraperJob' : ActorMethod<[bigint], [] | [ScraperJob]>,
  'getSenderIdentities' : ActorMethod<[], Array<SenderIdentity>>,
  'getSubscriptionByUser' : ActorMethod<[Principal], [] | [UserSubscription]>,
  'getWebsiteTemplate' : ActorMethod<[ClientId], [] | [WebsiteTemplate]>,
  'importCSVLeads' : ActorMethod<
    [Array<ImportRowResult>, string, string],
    ImportRecord
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllCampaigns' : ActorMethod<[], Array<OutreachCampaign>>,
  'listAllOutreachMessages' : ActorMethod<[], Array<OutreachMessage>>,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listConversionScripts' : ActorMethod<[], Array<ConversionScript>>,
  'listGrowthReports' : ActorMethod<[bigint], Array<GrowthReport>>,
  'listGrowthSuggestions' : ActorMethod<[ClientId], Array<GrowthSuggestion>>,
  'listLandingPages' : ActorMethod<[], Array<LandingPage>>,
  'listLeads' : ActorMethod<[], Array<Lead>>,
  'listLeadsByStatus' : ActorMethod<[LeadStatus], Array<Lead>>,
  'listNotesByLead' : ActorMethod<[LeadId], Array<Note>>,
  'listProposalsByLead' : ActorMethod<[LeadId], Array<Proposal>>,
  'listScraperJobs' : ActorMethod<[], Array<ScraperJob>>,
  'listSeoAudits' : ActorMethod<[], Array<SeoAuditRecord>>,
  'listWhatsAppTemplates' : ActorMethod<[], Array<WhatsAppTemplate>>,
  'markSuggestionImplemented' : ActorMethod<[SuggestionId], boolean>,
  'moveLead' : ActorMethod<[LeadId, LeadStatus], boolean>,
  'publishLandingPage' : ActorMethod<[LandingPageId], boolean>,
  'recordConsentLog' : ActorMethod<
    [string, string, ConsentType, string, string, string],
    ConsentLogId
  >,
  'recordDailyAction' : ActorMethod<[string], GamificationState>,
  'recordDeliveryStats' : ActorMethod<
    [SenderIdentityId, string, bigint, bigint, bigint, bigint, bigint],
    DeliverabilityStatId
  >,
  'runSeoAudit' : ActorMethod<[string], SeoAuditRecord>,
  'saveOnboardingPrefs' : ActorMethod<[string, string, bigint], undefined>,
  'saveWebsiteTemplate' : ActorMethod<[SaveTemplateInput], WebsiteTemplate>,
  'setGA4Credentials' : ActorMethod<[string, string], undefined>,
  'submitTemplateForApproval' : ActorMethod<[WhatsAppTemplateId], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformGA4' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCampaignStats' : ActorMethod<
    [bigint, bigint, bigint, string],
    OutreachCampaign
  >,
  'updateClientMetrics' : ActorMethod<[UpdateClientMetricsInput], boolean>,
  'updateConsentStatus' : ActorMethod<[ConsentLogId, ConsentStatus], boolean>,
  'updateLead' : ActorMethod<[UpdateLeadInput], boolean>,
  'updateOutreachMessageStatus' : ActorMethod<
    [bigint, string, [] | [Timestamp]],
    OutreachMessage
  >,
  'updateScraperJobProgress' : ActorMethod<
    [bigint, bigint, bigint, string],
    ScraperJob
  >,
  'updateSenderReputation' : ActorMethod<
    [SenderIdentityId, bigint, bigint, bigint, bigint],
    boolean
  >,
  'updateTemplateApprovalStatus' : ActorMethod<
    [WhatsAppTemplateId, WhatsAppTemplateStatus, [] | [string]],
    boolean
  >,
  'upsertMySubscription' : ActorMethod<[UserSubscription], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];